### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by TUCAOEVER** [ASangarin/MMOMana#1]
[23:54:54 ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] net.md_5.bungee.api.ChatColor.of(Ljava/lang/String;)Lnet/md_5/bungee/api/ChatColor; initializing MMOMana v1.2.3 (Is it up to date?)
java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.of(Ljava/lang/String;)Lnet/md_5/bungee/api/ChatColor;
        at eu.asangarin.mana.ManaConfig.getColorFromString(ManaConfig.java:50) ~[?:?]
        at eu.asangarin.mana.ManaConfig.loadOptions(ManaConfig.java:39) ~[?:?]
        at eu.asangarin.mana.MMOMana.onLoad(MMOMana.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:365) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by ASangarin** [comment]
Should be fixed in [1.2.4](https://github.com/ASangarin/MMOMana/releases/tag/1.2.4)
